name = "deliberation-empirica"
tajriba.store.file = "/data/tajriba.json" # for production, waiting on https://github.com/empiricaly/empirica/issues/383 before we can remove the default /data path

[tajriba.auth]
srtoken = "HErChTCtHqDuhziZ"

[[tajriba.auth.users]]
name = "Admin"
username = "admin"
password = "localpwd"
