name = "deliberation-empirica"
tajriba.store.file = ".empirica/data/tajriba.json"

[tajriba.auth]
srtoken = "HErChTCtHqDuhziZ"

[[tajriba.auth.users]]
name = "Admin"
username = "admin"
password = "localpwd"