version: '3'
services:
  empirica:
    platform: linux/amd64  # needed when developing on apple silicon
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  ngrok:
    image: wernight/ngrok
    command:
    - /bin/sh
    - -c
    - ngrok http --config /ngrok.yml --log stdout empirica:3000
    volumes:
    - ./ngrok.yml:/ngrok.yml
    depends_on:
    - empirica
