# For tests

version: '3'
services: 
  empirica-test:
    platform: linux/amd64  # needed when developing on apple silicon
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - EYESON_APIKEY=${EYESON_APIKEY}
    ports:
      - '3000:3000'
    volumes:
      - .empirica:/.empirica
    command:
      - empirica
      - serve
      - /app/deliberation.tar.zst
      - --dev
      - --log.level=trace