# For tests

version: "3"
services:
  empirica-test:
    platform: linux/amd64 # needed when developing on apple silicon
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TEST_CONTROLS=enabled
    environment:
      - DAILY_APIKEY=${DAILY_APIKEY}
      - PARTICIPANT_DATA_DIR=/participantData
      - SCIENCE_DATA_DIR=/scienceData
      - PAYMENT_DATA_DIR=/paymentData
      - EMPIRICA_DIR=/.empirica
      - TEST_CONTROLS=enabled
      - NODE_ENV2=development
    ports:
      - "3000:3000"
    volumes:
      - .empirica:/.empirica
      - ./deliberation-assets:/deliberation-assets # make it easy for server to access these files too
      - ./testData/participantData:/participantData
      - ./testData/scienceData:/scienceData
      - ./testData/paymentData:/paymentData
    command:
      - empirica
      - serve
      - /app/deliberation.tar.zst
      - --dev
      - --log.level=trace
