version: '3'
services:
  empirica-ngrok:
    platform: linux/amd64  # needed when developing on apple silicon
    build:
      context: .
      dockerfile: Dockerfile.ngrok
    volumes:
    - .:/app
    - /app/client/node_modules  # should ensure we don't clobber the container modules with the local.
    - /app/server/node_modules
