# For tests

version: "3"
services:
  empirica-test:
    platform: linux/amd64 # needed when developing on apple silicon
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TEST_CONTROLS=enabled
    environment:
      - DAILY_APIKEY=${DAILY_APIKEY}
      - QUALTRICS_DATACENTER=${QUALTRICS_DATACENTER}
      - QUALTRICS_API_TOKEN=${QUALTRICS_API_TOKEN}
      - PARTICIPANT_DATA_DIR=/data/participantData
      - SCIENCE_DATA_DIR=/data/scienceData
      - PAYMENT_DATA_DIR=/data/paymentData
      - EMPIRICA_DIR=/.empirica
      - TEST_CONTROLS=enabled
      - NODE_ENV2=test
    ports:
      - "3000:3000"
    volumes:
      - .empirica:/.empirica
      - ./testData/:/data
    command:
      - empirica
      - serve
      - /app/deliberation.tar.zst
      - --dev
      - --log.level=trace
