version: '3'
services:
  empirica:
    platform: linux/amd64  # needed when developing on apple silicon
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - EYESON_APIKEY=${EYESON_APIKEY}
    ports:
      - '3000:3000'  # empirica
      - "8844:8844"  # Vite HMR?
    volumes:
      - .:/app
      - /app/client/node_modules  # should ensure we don't clobber the container modules with the local.
      - /app/server/node_modules
    working_dir: /app
    command:
      - empirica

