version: '3'
services:
  empirica:
    platform: linux/amd64  # needed when developing on apple silicon
    build:
      context: .
      dockerfile: Dockerfile.cypress
    container_name: empirica
    volumes:
    - .:/app
    - /app/client/node_modules  # should ensure we don't clobber the container modules with the local.
    - /app/server/node_modules
    ports:
      - 3000:3000
  cypress:
    image: cypress
    build: ./client
    container_name: cypress
    depends_on:
      - empirica
    environment:
      - CYPRESS_baseUrl=http://localhost:3000
    network_mode: "host"
    command: npx cypress run
    volumes:
    - ./client/cypress:/app/cypress
    - ./client/cypress.json:/app/cypress.json
