# For deployment

version: "3"
services:
  empirica-prod:
    platform: linux/amd64 # needed when developing on apple silicon
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TEST_CONTROLS=disabled
    environment:
      - DAILY_APIKEY=${DAILY_APIKEY} # note these don't seem to get set on digitalOcean, need to do so manually in the settings webpage for the project
      - PARTICIPANT_DATA_DIR=/participantData
      - SCIENCE_DATA_DIR=/scienceData
      - PAYMENT_DATA_DIR=/paymentData
      - EMPIRICA_DIR=/.empirica
      - TEST_CONTROLS=disabled
      - NODE_ENV2=production
    ports:
      - "80:3000"
