version: 3.0.0

services:
  etherpad:
    build:
      context: .
    platform: linux/amd64
    ports:
      - "127.0.0.1:9001:80"
    environment:
      - DEFAULT_PAD_TEXT="Test etherpad default text"
      - DB_FILENAME=/opt/etherpad-lite/data/etherDB.sq3
      - APIKEY=doremiabc123babyyouandme

    volumes:
      - ./testData:/opt/etherpad-lite/data
    stdin_open: true
    tty: true
