name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: ["Watts-Lab/12"]

body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, what should have happened? Add screenshots, console logs, and other diagnostic info.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: checkboxes
    id: browsers
    attributes:
      label: What browsers do you see the problem on?
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: os
    attributes:
      label: What operating system do you see the problem on?
      multiple: true
      options:
        - label: Windows
        - label: Mac
        - label: Linux
  - type: checkboxes
    id: seen
    attributes:
      label: How did we discover the bug?
      description: Select multiple if relevant
      options:
        - label: Reported by participant
        - label: Observed on Sentry
        - label: Found in dev
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What is the (highest) consequence of the bug?
      options:
        - Blocking all data collection
        - Blocking a specific study
        - Blocking some participants
        - Inconvenience for participants
        - Inconvenience for researchers
        - Inconvenience for developers
        - Bad hygiene
      default: 0
    validations:
      required: true
