name: Run Cypress EyesOn Tests

on:
  workflow_dispatch

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cypress run  
      uses: cypress-io/github-action@v4.0.0
      with:
        # in theory the container should shut down automatically
        start: docker-compose -f ../docker-compose-dev.yml up -d
        working-directory: cypress
        browser: chrome
        record: true
        wait-on: 'http://localhost:3000'
        wait-on-timeout: 120
        spec: e2e/07_EyesOn_Check.js
      env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EYESON_APIKEY: ${{ secrets.EYESON_APIKEY }}

    # - name: Stop Empirica
    #   if: always()
    #   run: docker-compose -f "docker-compose-dev.yml" down
