name: Deploy to AWS App runner

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to AWS ECR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ECR_REGISTRY }}
          username: ${{ secrets.AWS_DEPLOY_ACCESS_KEY }}
          password: ${{ secrets.AWS_DEPLOY_SECRET_KEY }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            TEST_CONTROLS=disabled
            BUILD_SHA=${{ github.sha }}
          tags: |
            ${{env.ECR_REGISTRY}}/${{ env.REPO }}:latest
            ${{env.ECR_REGISTRY}}/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile
