name: Deploy to AWS Production

env:
  AWS_REGION: us-east-1 # N. Virginia

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read    # This is required for actions/checkout

jobs: 
  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3


      - name: Get AWS key/id using GH OIDC and save to .env
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::088838630371:role/deliberation-github-deploy
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GithubActionDeploy


      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time
        
      - name: Format timestamp as safe string
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Generate deployment package zipfile
        run: zip -r deploy-${{ steps.format-time.outputs.replaced }}.zip * -x "**node_modules**" -x '*.git*'

      ##
      
      # Testing on Yingquan's bucket; copying to S3.
      - name: Upload package to S3 bucket
        run: aws s3 cp ${{ steps.format-time.outputs.replaced }}.zip s3://myawsbucket-staging-yl/

      # Create an EB environment
      aws elasticbeanstalk create-environment --application-name deliberation --template-name v1 --version-label v1 --environment-name Deliberation-1

      # Creating an EB Application Version
      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name deliberation \
          --source-bundle S3Bucket="myawsbucket-staging-yl",S3Key="deploy-${{ steps.format-time.outputs.replaced }}.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      # Deploy to EB
      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name Deliberation-1 --version-label "ver-${{ github.sha }}"


      ## Old Deploy
      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v20
      #   with:
      #     aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
      #     aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
      #     aws_session_token: ${{ github.event.inputs.session_token }}
      #     application_name: deliberation
      #     environment_name: Deliberation-env
      #     version_label: "commit_${{ steps.format-time.outputs.replaced }}"
      #     region: ${{ env.AWS_REGION }}
      #     deployment_package: deploy-${{ steps.format-time.outputs.replaced }}.zip
