name: Deploy to AWS App runner

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to AWS ECR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          username: ${{ secrets.AWS_DEPLOY_ACCESS_KEY }}
          password: ${{ secrets.AWS_DEPLOY_SECRET_KEY }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            TEST_CONTROLS=disabled
            BUILD_SHA=${{ github.sha }}
          tags: |
            ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/deliberation-empirica:latest
            ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/deliberation-empirica:${{ github.sha }}
          file: ./Dockerfile
