name: entrypoint-bash

on:
  pull_request:
  push:
    branches: [main]

jobs:
  bash:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run entrypoint-helpers.test.sh
        run: bash entrypoint-helpers.test.sh
