name: ESLint on PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ESLint Packages
        run: npm install
      - name: Run ESLint
        run: echo "::set-output name=lint-result::$(npx eslint --ext .js --ext .jsx --ext .mjs client/src cypress server/src)"
        id: lint-script
      - uses: actions/github-script@v6
        with:
          script: |
            console.log("${{ steps.lint-script.outputs.lint-result }}")
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${{ steps.lint-script.outputs.lint-result }}" || "No Errors Found.",
            })
