name: ESLint on PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ESLint Packages
        run: npm install
      - name: Run ESLint
        continue-on-error: true
        run: npx eslint --ext .js --ext .jsx --ext .mjs -f html -o lintResult.html client/src cypress server/src
        id: lint-script
      - uses: actions/github-script@v6
        id: comment-result
        with:
          script: |
            import report from './lintResult.html';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report || "No Errors Found.",
            });
          result-encoding: string
      - name: Print Result
        run: echo "${{ steps.comment-result.outputs.result }}"
