name: Register etherpad container on GHCR

on:
  workflow_dispatch:

jobs:
  build_and_register:
    runs-on: "ubuntu-latest"

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        run: echo "BUNDLE_DATE=$(date +"%Y-%m-%d_%H-%M-%S")" >> $GITHUB_ENV

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            APIKEY=${{ secrets.ETHERPAD_APIKEY }}
            BUILD_SHA=${{ github.sha }}
            BUNDLE_DATE=${{ env.BUNDLE_DATE }}
          tags: |
            ghcr.io/deliberation-etherpad:latest
            ghcr.io/deliberation-etherpad:${{ env.BUNDLE_DATE }}
          file: ./Dockerfile
