name: Run Vitest

on:
  push:

jobs:
  run-vitest:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: cd server; npm install

      - name: Run vitest
        run: npm run test
